Module4 task1
htmlacademy-javascript/610981-kekstagram-28 pull request #3
Opened 2023-03-05 13:59 UTC by jdoroshina

2023-03-06 05:58 UTC, pavel-nyukalo requested changes

2023-03-06 05:58 UTC, pavel-nyukalo commented on js/main.js
> +const getRandomInt = (a, b) => {
Я бы предложил назвать эти переменные более осмыслено. Чтобы при прочтении функции глазами было понятно, что это за параметры мы передаем. Например, `min` и `max`

2023-03-06 07:52 UTC, jdoroshina commented on js/main.js
> +const getRandomInt = (a, b) => {
Я тоже про это думала, но меня смутило, что в коде уже есть min/max и это путает
`const getRandomInt = (a, b) => {
  const lower = Math.ceil(Math.**min**(a, b));
  const upper = Math.floor(Math.**max**(a, b));
  const result = Math.random() * (upper - lower + 1) + lower;
  return Math.floor(result);
};`

2023-03-06 19:00 UTC, jdoroshina commented on js/main.js
> +const getRandomInt = (a, b) => {
Исправила, как обговорили

2023-03-07 07:47 UTC, pavel-nyukalo approved these changes

2023-03-07 07:47 UTC, merged